# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: pratiche
---
# Secret per il registry privato
#
# Il docente lo ha configurato nel cluster.
# Non è necessario fare altro
#
#---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prta
  namespace: pratiche
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: prta
    spec:
      imagePullSecrets:
        - name: rt-devops-registry-01
      containers:
        - name: prta
          image: registry.digitalocean.com/rt-devops-registry-01/team_pratiche-prta:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: prta
  namespace: pratiche
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
